# Инструкции для nginx
server {
	# Следи за портом 80 на сервере с IP 127.0.0.1
	server_name 127.0.0.1 example.com;

	# Если в адресе запроса есть аргумент '/static/' - верни файл из этой директории
	location /static/ {
		root /home/user/yatube_project/yatube/;
	}

	# Медиа файлы
	location /media/ {
		root /home/user/yatube_project/yatube/;
	}

	# Любой другой запрос передай серверу Gunicorn
	location / {
		include proxy_params;
		# Передавать запросы нужно на внутренний IP на порт 8000
		proxy_pass http://127.0.0.1:8000;
	}
}
